//pub(crate) mod puzzle;
//pub(crate) mod region;
//mod row;
//mod regions;
//mod rows;
mod cell;
mod cells;
mod validate_cells;
mod column;
mod columns;
//mod collect_rows;
//mod collect_cols;
//mod collect_regions;
//mod test;
//mod validate_cells;