//pub(crate) mod puzzle;
//pub(crate) mod region;
//mod row;
//mod regions;
//mod rows;
mod cell;
mod cells;
mod col;
mod cols;
mod validate_cells;
mod collect_cols;
mod puzzle;
mod rows;
mod row;
mod collect_rows;
mod region;
mod regions;
mod collect_regions;
//mod collect_rows;
//mod collect_cols;
//mod collect_regions;
//mod test;
//mod validate_cells;